---
- name: Hippo CMS | Build a configurable, templated install of Hippo on Tomcat
  hosts: localhost
  connection: local
  sudo: True

  vars:
    ansible_pkg_mgr: apt

  roles:
    - williamyeh.oracle-java
    - daniel-rhoades.tomcat
    - daniel-rhoades.hippo-tomcat
